# NUMPY COMPLETE CHEATSHEET (ALL OPERATIONS)

# Array Creation - From list / tuple

In [51]:
a = np.array([1, 2, 3])
b = np.array((4, 5, 6))
print(a)
print(b)

[1 2 3]
[4 5 6]


# Zeros, Ones, Empty

In [52]:
c = np.zeros(5)
d = np.ones((2,3))
e = np.empty(4)
print(c)
print(d)
print(e)


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[5. 6. 7. 8.]


# Range-based

In [53]:
a = np.arange(0, 10, 2)
b = np.linspace(0, 1, 5)
print(a)
print(b)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


# Identity / Diagonal

In [54]:
a = np.eye(3)
b = np.identity(3)
c = np.diag([1,2,3])
print(a)
print(b)
print(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Array Attributes

In [55]:
a = np.array([[2,3],
     [4,5]])
print(a.ndim)     # dimensions
print(a.shape)     # rows, columns
print(a.size)      # total elements
print(a.dtype)     # data type
print(a.itemsize)  # bytes per element


2
(2, 2)
4
int32
4


# Data Types

In [56]:
a = np.array([1,2,3], dtype=float)
b = np.array([1,2,3], dtype=int)
c = np.array([1,0,1], dtype=bool)
print(a)
print(b)
print(c)
# Type conversion:
d = c.astype(float)
print(d)

[1. 2. 3.]
[1 2 3]
[ True False  True]
[1. 0. 1.]


# Indexing & Slicing

In [57]:
# 1D Indexing
a = np.array([10,20,30,40,50])

print(a[0])
print(a[-1])
print(a[1:4])
print(a[:3])
print(a[::2])


10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [58]:
# 2D Indexing
b = np.array([[1,2],[3,4],[5,6]])
print(b[0,1])
print(b[:,0])
print(b[1,:])


2
[1 3 5]
[3 4]


# Array Reshaping

In [59]:
a = np.array([10,20,30,40,50,60])
print(a.reshape(2,3)) # Changes the shape of the array
print(a.flatten()) # Converts array into 1D. Always returns a copy (new memory)
print(a.ravel()) # Converts array into 1D. Returns a view if possible (not a copy)
b = np.array([[1,2],
            [3,4],
            [5,6]])
print(b.transpose()) # Swaps axes (rows ↔ columns)
print(b.T) # Shortcut (property) for transpose()


[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]
[10 20 30 40 50 60]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


# Mathematical Operations

In [60]:
# Arithmetic
x = np.array([[1,2],
            [3,4]])
y = np.array([[5,6],
            [7,8]])
print(np.add(x, y))        # x + y
print(np.subtract(x, y))    # x - y
print(np.multiply(x, y))     # x * y
print(np.divide(x, y))       # x / y
print(np.power(x, y))        # x ** y
print(np.mod(x, y))          # remainder
print(np.remainder(x, y))
print(np.floor_divide(x, y))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[    1    64]
 [ 2187 65536]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


In [63]:
# Rounding & Approximation
x = [1,2,3.3,4.5,5.5,6.5,7.7,8]
print(np.round(x)) # round to nearest even
print(np.around(x)) # round is just an alias for around
print(np.floor(x)) 
print(np.ceil(x))
print(np.trunc(x))
print(np.fix(x))


[1. 2. 3. 4. 6. 6. 8. 8.]
[1. 2. 3. 4. 6. 6. 8. 8.]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1. 2. 4. 5. 6. 7. 8. 8.]
[1. 2. 3. 4. 5. 6. 7. 8.]
[1. 2. 3. 4. 5. 6. 7. 8.]


# Statistical Operations

# Dispersion & Percentiles

# Aggregation & Reduction

# Sorting & Searching

# Set Operations

# Linear Algebra (numpy.linalg)

# Matrix operations

# Random Number Generation (numpy.random)

# Input / Output Operations


# Masked Arrays (numpy.ma)

# Broadcasting System